version: '3.3'

services:
  server:
    build:
      context: .
      dockerfile: ./backend/dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/classes?serverTimezone=Australia/Sydney
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  client:
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - server

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: classes
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
  
volumes:
  db-data: 