name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: frontend
        run: npm ci

      - name: Linter
        working-directory: frontend
        run: npx eslint . --ext .tsx
            
      - name: Jest tests
        working-directory: frontend
        run: npm run test
 
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Keep this here in case maven doesn't work on Github Action: see bug with Act
      # - name: Download Maven
      #   working-directory: backend
      #   run: |
      #     curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
      #     apt-get update
      #     apt-get -y install unzip
      #     unzip -d /usr/share maven.zip
      #     rm maven.zip
      #     ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
      #     echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment

      - name: Junit tests
        working-directory: backend
        run: mvn clean test
        
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Deploy
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name uq_degree_planner \
            --deployment-group-name planner_deployment_group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}