name: CI/CD
on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-2                   
  ECR_REPOSITORY: uq_degree_planner           
  ECS_SERVICE: uq-degree-planner-service                 
  ECS_CLUSTER: uq-degree-planner-cluster                 
  ECS_TASK_DEFINITION: task.json 
  CONTAINER_NAME: uq_degree_planner           

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: frontend
        run: npm ci

      - name: Linter
        working-directory: frontend
        run: npx eslint . --ext .tsx
            
      - name: Jest tests
        working-directory: frontend
        run: npm run test
 
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Junit tests
        working-directory: backend
        run: mvn clean test
        
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name uq_degree_planner \
            --deployment-group-name planner_deployment_group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}